### PR TITLE
Editable

### PR DESCRIPTION
**Pull request by jlank**
@acolochado,

I like your chrome extension and decided to enhance it, hopefully you find my changes useful.  Basically, the use case I wanted to support was not only examining query string parameters, but also having the ability to edit them and test the edits in a new tab.  Therefore, I changed the popup to have the values displayed in a content editable div.  Once you make the changes you want, you just hit enter and they take effect in a new tab.  I also added the ability to add new parameters, and I add parsing of the #hash values (assuming they have the same key=value& syntax of the query string) -- google.com's hash maintains that convention.

Thanks!
@jlank

### CODE REVIEW

**Comment by jlank** [comment]
:+1: ? :-1: ?

**Comment by acolchado** [comment]
@jlank I am sorry, I hadn't seen this notification come up. I will take a look and get back to you. I like what you're describing above. 

Sorry again for the delay.

**Comment by jlank** [comment]
No worries I've been using it for a while locally. It's useful!

**Comment by HugeLandMonster** [comment]
Editable Pull Request looks good; It provides the needed functionality to make the extension practical and usable.  Good Job @jlank!

@jlank To improve UI intuitiveness, the two "add row" and "go" arefs, should be capcase and styled as CSS buttons making it obvious to the user that they are controls.  

@acolchado How come this commit has not been added to the master branch?

**Pull request merged**
